version: "3.7"

services:

  mysql-db:
    container_name: mysql-db
    restart: always
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: Rootroot
      MYSQL_ROOT_PASSWORD: Rootroot
    networks:
      - mediscreen-network
    ports:
      - '3307:3306'
    volumes:
      - ./patient/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  patient-service:
    container_name: patient-service
    restart: always
    build: patient/
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: Rootroot
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mediscreen
    depends_on:
      - mysql-db
    networks:
      - mediscreen-network
    ports:
      - '8081:8081'

  mongo-db:
    container_name: mongo-db
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - mediscreen-network
    ports:
      - '27017:27017'
    volumes:
      - ./medical-record/data:/data/db

  medical-record-service:
    container_name: medical-record-service
    restart: always
    build: medical-record/
    environment:
      MONGODB_HOST: mongo-db
      MONGODB_USER: admin
      MONGODB_PASSWORD: pass
      MONGODB_PORT: 27017
      MONGODB_DATABASE: mediscreen
    depends_on:
      - mongo-db
    networks:
      - mediscreen-network
    ports:
      - '8082:8082'

  assessment-service:
    container_name: assessment-service
    restart: always
    build: assessment/
    environment:
      PATIENT_SERVICE_URL: http://patient-service:8081
      MEDICAL_RECORD_SERVICE_URL: http://medical-record-service:8082
    depends_on:
      - patient-service
      - medical-record-service
    networks:
      - mediscreen-network
    ports:
      - '8080:8080'

  angular:
    container_name: front
    build: medapp/
    depends_on:
      - assessment-service
    networks:
      - mediscreen-network
    ports:
      - "4200:4200"

networks:
  mediscreen-network:
    driver: bridge